name: Release

on:
  push:
    branches:
      - main

env:
  NOTION_VERSION: "3.14.0"

  # Increament if fixing same notion version, otherwise should be zero
  SUB_RELEASE: "0"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: wget https://desktop-release.notion-static.com/Notion-${NOTION_VERSION}.dmg

      - name: Extract
        run: |
          7z x "Notion-${NOTION_VERSION}.dmg" "Notion/Notion.app/Contents/Resources/app.asar" "Notion/Notion.app/Contents/Resources/app.asar.unpacked"
          npx asar e "Notion/Notion.app/Contents/Resources/app.asar" "asar_patched"

      - name: Replace BufferUtil
        run: |
          VERSION=$(jq -r '.dependencies["bufferutil"]' asar_patched/package.json)
          mkdir bufferutil && cd bufferutil
          echo "Going to install bufferutil: $VERSION"
          npm install --no-save "bufferutil@${VERSION}"
          cd ..
          mv bufferutil/node_modules/bufferutil/prebuilds/linux-x64/node.napi.node asar_patched/node_modules/bufferutil/build/Release/bufferutil.node
          rm -rf bufferutil

      - name: Replace Better SQLite
        run: |
          VERSION=$(jq -r '.dependencies["better-sqlite3"]' asar_patched/package.json)
          mkdir better_sqlite3 && cd better_sqlite3
          echo "Going to install better_sqlite3: $VERSION"
          npm install --no-save "$VERSION"
          cd ..
          mv better_sqlite3/node_modules/better-sqlite3/build/Release/better_sqlite3.node asar_patched/node_modules/better-sqlite3/build/Release/
          rm -rf better_sqlite3

      - name: Patch
        run: |
          # removing some unnecessary files
          rm "asar_patched/node_modules/node-mac-window" -r
          rm "asar_patched/node_modules/better-sqlite3/build/Release/test_extension.node"
          rm asar_patched/*.provisionprofile
          rm "asar_patched/icon.icns"

          # adding tray icon to the unpacked resources
          cp "notion.png" "asar_patched/.webpack/main/trayIcon.png"

          # fully disabling auto updates
          sed -i 's/if("darwin"===process.platform){const e=s.systemPreferences?.getUserDefault(E,"boolean"),t=_.Store.getState().app.preferences?.isAutoUpdaterDisabled;return Boolean(e||t)}return!1/return!0/g' "asar_patched/.webpack/main/index.js"

          # disabling the app menu since most of the options won't work
          sed -i 's/Menu.setApplicationMenu(p(e))/Menu.setApplicationMenu(null)/g' "asar_patched/.webpack/main/index.js"

          # fixing tray icon and right click menu
          sed -i 's|this\.tray\.on("click",(()=>{this\.onClick()}))|this.tray.setContextMenu(this.trayMenu),this.tray.on("click",(()=>{this.onClick()}))|g' "asar_patched/.webpack/main/index.js"
          sed -i 's|getIcon(){[^}]*}|getIcon(){return s.default.join(__dirname, "trayIcon.png");}|g' "asar_patched/.webpack/main/index.js"

          # avoid running duplicated instances, fixes url opening
          sed -i 's/a\.app\.on("open-url",_.handleOpenUrl)):"win32"===process\.platform/a\.app\.on("open-url",_.handleOpenUrl)):"linux"===process\.platform/g' "asar_patched/.webpack/main/index.js"

      - name: Archive
        run: |
          npx asar p "asar_patched" "app.asar" --unpack *.node
          echo '{"productName":"Notion"}' > package.json
          tar cvf notion-linux.tar app.asar app.asar.unpacked package.json

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NOTION_VERSION }}-${{ env.SUB_RELEASE }}
          files: notion-linux.tar
